/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FwDatepicker {
    'currentDate': string;
    'dateFormat': string;
    'label': string;
    'maxYear': number;
    'minYear': number;
    'required': boolean;
  }
  interface FwDropdown {
    'label': string;
    'placeholder': string;
    'required': boolean;
    'state': string;
  }
  interface FwInput {
    'label': string;
    'placeholder': string;
    'required': boolean;
    'state': string;
    'stateText': string;
    'value': string;
  }
  interface FwTag {
    'state': string;
    'text': string;
    'tooltip': string;
  }
}

declare global {


  interface HTMLFwDatepickerElement extends Components.FwDatepicker, HTMLStencilElement {}
  var HTMLFwDatepickerElement: {
    prototype: HTMLFwDatepickerElement;
    new (): HTMLFwDatepickerElement;
  };

  interface HTMLFwDropdownElement extends Components.FwDropdown, HTMLStencilElement {}
  var HTMLFwDropdownElement: {
    prototype: HTMLFwDropdownElement;
    new (): HTMLFwDropdownElement;
  };

  interface HTMLFwInputElement extends Components.FwInput, HTMLStencilElement {}
  var HTMLFwInputElement: {
    prototype: HTMLFwInputElement;
    new (): HTMLFwInputElement;
  };

  interface HTMLFwTagElement extends Components.FwTag, HTMLStencilElement {}
  var HTMLFwTagElement: {
    prototype: HTMLFwTagElement;
    new (): HTMLFwTagElement;
  };
  interface HTMLElementTagNameMap {
    'fw-datepicker': HTMLFwDatepickerElement;
    'fw-dropdown': HTMLFwDropdownElement;
    'fw-input': HTMLFwInputElement;
    'fw-tag': HTMLFwTagElement;
  }
}

declare namespace LocalJSX {
  interface FwDatepicker {
    'currentDate'?: string;
    'dateFormat'?: string;
    'label'?: string;
    'maxYear'?: number;
    'minYear'?: number;
    'required'?: boolean;
  }
  interface FwDropdown {
    'label'?: string;
    'placeholder'?: string;
    'required'?: boolean;
    'state'?: string;
  }
  interface FwInput {
    'label'?: string;
    'placeholder'?: string;
    'required'?: boolean;
    'state'?: string;
    'stateText'?: string;
    'value'?: string;
  }
  interface FwTag {
    'state'?: string;
    'text'?: string;
    'tooltip'?: string;
  }

  interface IntrinsicElements {
    'fw-datepicker': FwDatepicker;
    'fw-dropdown': FwDropdown;
    'fw-input': FwInput;
    'fw-tag': FwTag;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'fw-datepicker': LocalJSX.FwDatepicker & JSXBase.HTMLAttributes<HTMLFwDatepickerElement>;
      'fw-dropdown': LocalJSX.FwDropdown & JSXBase.HTMLAttributes<HTMLFwDropdownElement>;
      'fw-input': LocalJSX.FwInput & JSXBase.HTMLAttributes<HTMLFwInputElement>;
      'fw-tag': LocalJSX.FwTag & JSXBase.HTMLAttributes<HTMLFwTagElement>;
    }
  }
}


